### ISSUE TITLE
CraftChatMessage error

### ISSUE THREAD

**Issue by nebula161** [CivMC/CivModCore#24]
There are a few exceptions caused by CivModCore starting with `java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/util/CraftChatMessage
at vg.civcraft.mc.civmodcore.chat.ChatUtils.stringify(ChatUtils.java:304)` and originating [here](https://github.com/CivMC/CivModCore/blob/master/paper/src/main/java/vg/civcraft/mc/civmodcore/chat/ChatUtils.java) 

https://github.com/CivMC/Finale/issues/14
https://github.com/CivMC/Finale/issues/13
https://github.com/CivMC/FactoryMod/issues/19

**Comment by Diet-Cola** [comment]
Are you compiling this version of civmodcore? That class points to 1.18.2 here but your error states 1.18.1

**Comment by nebula161** [comment]
I used whatever version is on CivDocker.

**Comment by Diet-Cola** [comment]
@wingzero54 @AngrySoundTech

**Comment by wingzero54** [comment]
Get the new CivModCore jar, I totally forgot that CMC needs to be re-obfuscated after building it, so the CMC jar I had uploaded was actually two months old and did not include the 1.18.2 updates https://github.com/CivMC/CivDocker/tree/master/paper/plugins
